/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BingoIndexRouteImport } from './routes/bingo/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BingoIndexRoute = BingoIndexRouteImport.update({
  id: '/bingo/',
  path: '/bingo/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bingo/index.lazy').then((d) => d.Route))
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/about-us/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/bingo': typeof BingoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/bingo': typeof BingoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/bingo/': typeof BingoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about-us' | '/bingo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-us' | '/bingo'
  id: '__root__' | '/' | '/about-us/' | '/bingo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  BingoIndexRoute: typeof BingoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo/': {
      id: '/bingo/'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  BingoIndexRoute: BingoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
